archive:
  type: "s3"
  url: "http://s3"
  port: 9000
  accesskey: "access"
  secretkey: "secretkey"
  bucket: "archive"
  chunksize: 32

aws:
  url: "http://s3:9000"
  readypath: "/minio/health/ready"
  accessKey: "access"
  secretKey: "secretkey"
  bucket: "inbox"
  region: "us-east-1"

broker:
  host: "rabbitmq"
  port: 5672
  user: ""
  password: ""
  vhost: "gdi"
  queue: ""
  exchange: "sda"
  routingKey: ""
  routingError: "error"
  ssl: "false"

c4gh:
  passphrase: "c4ghpass"
  filepath: "/shared/c4gh.sec.pem"
  backupPubKey: "/shared/c4gh.pub.pem"

db:
  host: "postgres"
  port: 5432
  user: ""
  password: ""
  database: "lega"
  sslmode: "disable"

inbox:
  type: "s3"
  url: "http://s3"
  port: 9000
  accesskey: "access"
  secretkey: "secretkey"
  bucket: "inbox"
  chunksize: 32

log:
  level: "debug"
  format: "json"

schema:
  type: isolated

server:
  jwtpubkeypath: "/shared/keys/pub/"
  jwtpubkeyurl: ""